---
title: "Homework  5"
author: "STA 601L: Bayesian and Modern Statistics"
#date: "`r format(Sys.time(), '%d %B, %Y')`"
date: "Sept 26, 2021"
output: 
  tufte::tufte_html:
    tufte_variant: "envisioned"
    highlight: pygments
    toc: true
link-citations: yes
---

```{r include=FALSE}
library(tidyverse)
library(tufte)
library(knitr)
options(
  htmltools.dir.version = FALSE, # for blogdown
  show.signif.stars = FALSE,     # for regression output
  digits = 2
  )
knitr::opts_chunk$set(eval = FALSE)
```

**Due:**  October 25 11pm



## R Knitr

You are required to use R knitr with the Rnw format to type up this lab report.  To get started see [basics](https://kbroman.org/knitr_knutshell/pages/latex.html) about knitr.


# Getting started

Go to Github classroom to  accept the invitation to create a repository for this assignment  at [HW5](https://classroom.github.com/a/fcpuy2UD)

This will create a private repo in the organization on Github with your github user name. 

Hit refresh, to see the link for the repo, and then click on it to go to the repo in the organization in Github.

Follow the instructions in the README in your repo and in the  Rnw file to complete the assignment. 

## Github Classroom & Gradescope

You MUST submit your final `Rnw` and  `pdf` files to the repo on Github and upload the `pdf` to Gradescope here: https://www.gradescope.com/courses/431637.  Please remember to push your updates to GitHub regularly.


## Grading

Total: 20 points.
  